### ISSUE TITLE
-f flag fails to build a parser.

### ISSUE THREAD

**Issue by Lucretia** [Ada-France/ayacc#2]
Adding the -r flag fails to build stating an illegal filename, passing a filename works. 

This isn't documented.

**Comment by stcarrez** [comment]
Thanks!

**Comment by stcarrez** [comment]
The `-r` option was declared to consume an argument but this was wrong.
I've fixed this.
Now, it is not clear to me how the Ayacc error recovery improvement can used used.

**Comment by stcarrez** [comment]
Ok, I've found the process to use it and the generated code is broken now.

```
aflex -E calc_lex.l`
gnatchop -w calc_lex.ada
gnatchop -w calc_error_report.ada
ayacc -r calc.y
gnatchop -w calc.ada
```
what is now missing is a `with calc_error_report;` in the parser file. I'm going to fix it.

**Comment by stcarrez** [comment]
Ok, the generated code is correct and to use it the grammar must also include

```
with calc_error_report;
```
I'm closing this now.
