### ISSUE TITLE
Syntax Error doesn't show line number

### ISSUE THREAD

**Issue by zertovitch** [Ada-France/ayacc#3]
The parser generated by Ayacc doesn't show the line number of a parsed file when it meets a syntax error.
Then it's difficult to spot an error on a large file to be parsed.
Fortunately the solution is already programmed in the aflex & ayacc available with p2ada ([here](https://github.com/zertovitch/pascal-to-ada)).

parse_template_file.adb, line 351

         Create ("         if yy.error_flag = 0 then --  brand new error"),
     >>  Create ("            yyerror (""Syntax Error"");"),
         Create ("-- UMASS CODES :"),
         Create ("            yy_error_report.Put_Line ( ""Skipping..."" );"),
         Create ("            yy_error_report.Put_Line ( """" );"),
         Create ("-- END OF UMASS CODES."),
         Create ("         end if;"),

In the "p2ada" version:

         Create ("    if yy.error_flag = 0 then -- brand new error"),
         Create ("-- UMASS CODES :"),
         Create ("        yy_error_report.put_line ( ""Skipping..."" );"),
         Create ("        yy_error_report.put_line ( """" );"),
         Create ("-- END OF UMASS CODES."),
         Create ("        if yy_io.Input_Line > 1 then"),
     >>  Create ("            yyerror(""Syntax Error at line"" & Text_IO.Count'Image(yy_io.Input_Line));"),
         Create ("        else"),
         Create ("            yyerror(""Syntax Error at line 1 (or possibly later and the AFLex -E option was omitted)."");"),
         Create ("        end if;"),
         Create ("    end if;"),

**Comment by stcarrez** [comment]
I think the `%option yylineno` gives more flexibility and control to report line number either in error but also later.
Together with the `yylineno` variable, we have the `yylinecol` which indicates the starting column of the lex symbol.

**Comment by zertovitch** [comment]
Thanks, I'll have a look!

**Comment by zertovitch** [comment]
If I add `%option yylineno` in the .l file, the lexer generator produces somewhere a variable `yylineno`.

    package rc_dfa is
       aflex_debug       : Boolean := False;
       yylineno          : Natural := 0;
       yylinecol         : Natural := 0;

That's the good news. But GNAT Studio finds only that reference in the whole software which includes the lexer and the parser. So `yylineno` won't be incremented. And there should be `yylineno := yylineno + 1;` generated somewhere else (looking in aflex' sources). Any clue ? Perhaps the placement of the `%option` ?

**Comment by zertovitch** [comment]
Now I've sandboxed the experiment and the increment appears in `yylex.adb`. The wrong version was obviously still there (probably the reason is that the file `rc.ada` (in my test for `rc.l`, `rc.y`) contains actually the `yylex.adb` or `yyparse.adb` files depending on which tool (aflex or ayac) generated it. Ooof!

**Comment by zertovitch** [comment]
A follow-up: by testing with an error injection into a `.rc` file to be parsed, `yylineno` gives a line number that is larger (ofter, much larger, like 100 lines away) than the actual line where the syntax error occurred. It is perhaps the point that was last read by the lexer, but the parser is behind (buffering, tokenization, etc.).
For pointing to a syntax error `yylineno` is less useful. So I think it would be a useful to revive the `yy_io.Input_Line` information for locating syntax errors.

**Comment by stcarrez** [comment]
Ok, the `Input_Line` function was always returning 1 and was not functional in the previous version.
Now, I suspect you'll get almost the same result.

To track and report errors in an accurate manner, I'm using a `YYSType` that records the line and column of the expression. The line and column is recorded by using the symbol location. For example, I'm using the following type:

```
   type YYstype is new Ada.Finalization.Controlled with record
      Line     : Natural    := 0;
      Column   : Natural    := 0;
      Unit     : CSS.Core.Values.Unit_Type  := CSS.Core.Values.UNIT_NONE;
      Kind     : Node_Type := TYPE_NULL;
      Sel      : CSS.Core.Selectors.Selector_Type := CSS.Core.Selectors.SEL_CLASS;
      Node     : Parser_Node_Access;
   end record;
```

Then when I have to handle an error, I avoid using the default `yyerror` mechanism because it does not
give useful message by itself, but I take care of adding the error symbol that catches errors:

```
ruleset :
    rule_selectors spaces rule_declaration_list '}' spaces
       { Current_Rule := null; }
  |
    rule_selectors spaces error '}' spaces
       { Current_Rule := null; Error ($4.line, $4.column, "Invalid CSS rule"); }
  |
    rule_selectors spaces '}' spaces
       { Current_Rule := null; }
  |         
    error '}' spaces
       { Error ($1.Line, $1.Column, "Syntax error in CSS rule"); }
  ;
```

Here, I don't use the `yylineno` as is but the line number that was saved when the associated symbol was found.
This way, I'm getting quite accurate error messages.

**Comment by zertovitch** [comment]
It's a bit tricky: if alfex (the old / "p2ada" one) is called without the `-E` option, it generates:

      function Input_Line return Text_IO.Count is
        l: Text_IO.Count := 1;
      begin
        return l; -- from file, always 1
        -- if is_open(user_input_file) then
        --   return Text_IO.Line(user_input_file);
        -- else
        --   return Text_IO.Line;
        -- end if;
      end Input_Line;

so actually it returns always 1, but with the `-E` option, it generates:

      function Input_Line return Text_IO.Count is
        l: Text_IO.Count := 1;
      begin
    -- UMASS CODES :
        l:= Text_IO.Count(Line_Number_Of_Saved_Tok_Line2);
    -- END OF UMASS CODES.
        return l; -- from file, always 1
        -- if is_open(user_input_file) then
        --   return Text_IO.Line(user_input_file);
        -- else
        --   return Text_IO.Line;
        -- end if;
      end Input_Line;

which works like a charm...

**Comment by stcarrez** [comment]
I've made a correction on Aflex to generate the `Input_Line` when `-E` option is used.

**Comment by zertovitch** [comment]
I think we are almost there.
Here is a patch against commit 8663f75f8172750c8957ff4017b3ded9edad266a to resurrect
the generation of the line "package yy_io renames ..."
[yy_io.patch](https://github.com/Ada-France/ayacc/files/11582530/yy_io.patch)

Then, in `body-ayacc.adb`, line 271, if you replace

        yyerror ("Syntax Error");

by

        if yy_io.Input_Line > 1 then
            yyerror ("Syntax Error at line" & yy_io.Input_Line'Image);
        else
            yyerror ("Syntax Error");  --  Really line 1, or aflex without option -E was used.
        end if;

...we should be done with this issue.

**Comment by stcarrez** [comment]
Almost...

1. `Input_Line` is defined only when `aflex -E` is used so we cannot make this the default.
2. The `IO_Unit_Name` function generates a package name based on the ayacc grammar name but it refers to a package for the lexer.  In my case, it generates `Parser_IO` for the `yy_io` renames but my package is named `Lexer_IO` so it does not compile.

One way to fix 1) could be to improve the new `%define parse.error` configuration (whose name comes from [bison 3.8](https://www.gnu.org/software/bison/manual/html_node/_0025define-Summary.html) to activate a more detailed syntax error message:

```
%define parse.error {simple|line|extended}
```

* `simple` would be the default with no `Input_Line` and a simple `"syntax error"` message,
* `line` would rely on an `yylineno` function or variable to emit a `"syntax error at line"` message,
* `extended` would also activate the `ayacc` error recovery.

And one day we could try to implement Bison detailed report mode with their LAC (lookahead correction).

To fix 2) I would suggest that this is handled by users within the grammar by using the new `%code decl` code block.
In your case, you would define the following:

```
%code decl {
      function yylineno return Ada.Text_IO.Count renames <lexer_package>_IO.Input_Line;
}
```

On my side, I would use the `yylineno` variable:

```
%code decl {
      function yylineno return Natural is (<lexer_package>_DFA.yylineno);
}
```

and for a re-entrant parser I would use:

```
%code decl {
      function yylineno return Natural is (Context.yylineno);
}
```

This would give us quite some more flexibility.

What do you think?

**Comment by zertovitch** [comment]
I am rather on the user side of those tools. If there is a simple way to get back the output of the line when a syntax error occurs, I am happy (and would be happy to remove the copies of aflex/ayacc scattered in various projects). By "simple way" I mean adding max a small fixed amount (including zero :-) ) of lines of code in the .l, .y and helper files.

**Comment by zertovitch** [comment]
Thinking loud... What about producing the `Input_Line` function also without the `-E` option?
`yy_io` and `IO_Unit_Name` were tentative names (sorry for not mentioning that; I cannot rebuild the templates and test the whole). You could use anything else that fits the compiler.

**Comment by stcarrez** [comment]
Putting back `Input_Line` that returns `1` in all case will not solve problem 2)

Today, the generated template only rely on the `YYLex` function that could be implemented without `aflex` and written manually. By adding the `yy_io` package rename declaration, we bring a dependence to a package that could not exist and for which we don't have the real name.  Guessing that name from the Ayacc parser unit name does not work.

The alternative could be that we require a function to be visible together with `YYLex` function. Then `yy_io` package rename declaration is not used. There are two ways for that function to be available:

* Declared by the user in the `aflex` lexer package specification (as the user do with `YYLex`),
* Declared within the `%code decl` code block in the `ayacc` grammar

If we add a requirement on the Lexer, I would suggest that we use some `YY` prefix to follow some existing convention and make it clear this is tied to the `YYLex` function.

**Comment by stcarrez** [comment]
Since the `yyerror` procedure is provided by the ayacc grammar, a third alternative is to handle the `Input_Line` test and format within that procedure body.  This gives even more flexibility because you are free to decide where you put the line number.

You could generate a message like:

```
<file>:<lineno>: Syntax error
```

as well as:

```
Syntax Error at line <line>
```

One issue with the following in the generated template:

```
yyerror ("Syntax Error at line" & yy_io.Input_Line'Image);
```
is that you cannot change the format if you wish to: it's hard coded in the `Ayacc` generator.

**Comment by zertovitch** [comment]
Brillant solution!
Indeed, the grammar programmer provides the procedure `yyerror` *and* is responsible for calling aflex with the correct options. And `yyerror` is called only from the code point we are discussing.
Nevertheless, I test your idea using P2Ada as ginea pig (https://github.com/zertovitch/pascal-to-ada).

```
with Pascal_IO;
with Ada.Text_IO;

procedure YYError (S : IN String) IS
  syntax_error : exception;
begin
  Ada.Text_IO.Put_Line (S);
  Ada.Text_IO.New_Line;
  Ada.Text_IO.Put_Line
   ("Syntax error in Pascal source, line number:" &
    Pascal_IO.Input_Line'Image);
  --  ^ NB: the function `Pascal_IO.Input_Line` is generated
  --  or is working correctly *only* when AFlex is called
  --  with the `-E` option.
  raise syntax_error;
end YYError;
```
Output with old ayacc & aflex pair currently shipped with P2Ada, on a faulty Pascal source:
```
  type  MySet  is  array (  Syntax Error at line 20

Syntax error in Pascal source, line number: 20
```
Redundant but it is expected. And the new custom message is clearer.
Now a test with the new ayacc & aflex:

```
  type  MySet  is  array (  Syntax Error

Syntax error in Pascal source, line number: 20
```
So the translators can be generated by both pairs of aflex & ayacc without any change needed when switching the toolsets (old vs. new aflex & ayacc pairs)!

Congrats for the very simple solution!

**Comment by zertovitch** [comment]
P2Ada was updated as described above: https://github.com/zertovitch/pascal-to-ada/commit/fed913e5d04a26271dada2c53be596e995e1f68d
