### ISSUE TITLE
Issue with private packages

### ISSUE THREAD

**Issue by zertovitch** [Ada-France/ayacc#8]
On some projects involving an ayacc grammar, the compilation of `yyparse.adb` stops with the following error:

```
yyparse.adb:6:17: current unit must also be private descendant of "Standard"
yyparse.adb:6:34: current unit must also be private descendant of "Standard"
```

It happens on a WITH clause:
```
with RC_Tokens, RC_Shift_Reduce, RC_Goto, RC_Help, RC_IO;
                17               34
---------------/----------------/
```
The reason is that the *_Goto and *_Shift_Reduce packages are newly private:
goto_file.adb:
`      Write_Line ("private package " & Goto_Tables_Unit_Name & " is");
`      
shift_reduce_file.adb:
`      Write_Line ("private package " & Shift_Reduce_Tables_Unit_Name & " is");
`
A solution could be to make this privacy optional (or just remove it).

**Comment by stcarrez** [comment]
The `private package` makes sense to reduce the scope and visibility of these two generated packages. It enforces the fact they are internal to the parser.

If the parser is not declared in a package, it is an error to make it `private` and we should not do this.

**Comment by stcarrez** [comment]
The `calc` example works and compiles. It generates the following packages:

```
private package Calc_Goto
private package Calc_Shift_Reduce
package parser
```

and they are withed correctly without error from `parser` body:

```
with yylex, calc_lex_dfa, calc_lex_io, text_io, calc_tokens, calc_goto, calc_shift_reduce; 
```

What makes it different from your example?

**Comment by zertovitch** [comment]
`yyparse` is a procedure which can be even be built as a main procedure. And it has (unfortunately) no explicit common ancestor with `calc_goto` and `calc_shift_reduce`.
An idea would be to make (optionally) all those guys children of the same top package. It would be cleaner and would allow for having multiple parsers in the same sources set.

But back to the testing:
- this one is working: https://github.com/zertovitch/pascal-to-ada/tree/master/newp2ada/current
- this one produces the compilation error : https://github.com/zertovitch/gwindows/tree/master/gwenerator/src
Fortunately the 2nd translator is easier to handle
`aflex -i -E RC.l`
`gnatchop -w rc.ada`
`ayacc RC.y`
`gnatchop -w rc.ada`
`gprbuild -Pgwenerator rc2gw`

Incidentally, I can also do `gprbuild -Pgwenerator yyparse` successfully. It is useless, but possible...

**Comment by zertovitch** [comment]
Now I have seen from your example that you have wrapped `yyparse` into a package from the `.y` file. Nice!
But it is a bit a "soft" trick since you can still write a package
```
package gogol is 
  procedure yyyppeeee; 
end gogol; 
```

```
with calc_goto, calc_shift_reduce;  --  NB: private library packages (10.1.1 (12))
package body gogol is
  procedure yyyppeeee is
  begin
    null;
  end;
end gogol; 
```
Just to illustrate that `calc_goto`, `calc_shift_reduce` are not internal to anything. But agreed, the `private` makes a misuse a bit more convoluted. I still think that `calc.*` for everything (parser and lexer) would be much cleaner.

**Comment by zertovitch** [comment]
For the fun of it, here is a patch for the `calc` example where `yylex` is wrapped as well into a package.
[calc.patch](https://github.com/Ada-France/ayacc/files/11681872/calc.patch)
Finally, everything in the parser/lexer has a `calc_` prefix.
